language: java
jdk:
- oraclejdk11
env:
  global:
  - secure: Y5V7pA20f6+jKyi2EZmXCHnLGrNjf4fiVH50HcNnaONV3t6+kTJgItf5aTin0vT/hKfmhm9wcsXq8row2yaJT7XcO5X9Y24YtPbH8RmIXafN+RD7McZl96wyoU1VmBmDE0CfKONjhSz4yPPFMVezrXY+unOqhFVSMswGz6oQ/qZZ1o1xjCjyoUm9J6g91YqKmyK/V2PnSGSQWfgcK+EYvxTyZJeMXOnjOL6Cx9pKBSMjBEu50FzXhvG0drHWLpHbb0D0c7LRDAA59H59j0vUAxgnTHbDY5Diitv5zI9QsrpyPAfMl+DHwjYVXfopjH1EVXfP106P77p9BH0a0X0qEDQ556XN4YvcKUtqgk6ijljRZn3hXYwdD9ZAFLe5OxChFc7RcKmnJnI7/x26OtvJ5Z9227jiLuEO2U1uy3riMiD7YhEMEqXbLRCKgkV/WqSxh56pqhR4T3XClOV9gL0LIuTr7gqZANpy1eQL5bLJMSUB1WTt/UlcIM1EYqjgKmOJ5tCEkgat1zhD6HoOg1V9oolzDL9JiCbneVO0HEi6T0Tiiz5C1JxnTT+T1J68WltCwaw9s4jctc9e2NQEth/qID+I7cYKzY7ybCwzllcjSnE11IJpL5xj7xMq/Mq5U2ivuR4XeGITkZG2LtfXfez22NJS0Wxf3KNOcrWy/N1qjxg=
  - secure: VhbOcNqJ1NBljGbbbTrvaFmwcVaGfZPOXg14eWr3RB8e/UcTIdW16S5oGWbFwmoCLdmyj01Lu8zgkxnkoIoGWG0/yI+4ocQ2TPFS3NzsTJ51qKpvOmLBOH6FNHDudCI16XnoIs4H7spf18NCGHPDUGqIA+B0BttUyXOAcW+3AylR3zaEc1hvccPlSvedWu1YWT/+P1E4Xztaiul2bXbzEq+bkYO43CR72Q8V/7vVBJYlC5re/T4vxhYT7+xgWfkblDQFhPWIKju5XYFLfvzYg/FzY+tYbRpzBwPREdyz9ahIlZARQgBE6j8gQ+W2hVPR+ckpUZXFEYVGbTn/j9Y6VjHakgN9/IuCj/Epz88lQG4dMKjz+iUnsTX0/kE175SQyltbkkBarJaLayAaHoVIJ+IMig49s0EQMjZuPZgOzD5CJqQjP2btuyJ5CZizKvbjfIeS0RDKlJiSw0at8r4EBIEAt25uaHH4vl+fJBGCXXCC5H7pLPqKRabLyZJx8tcSjTHXtSuUR+L3kFEr1ALpJB7brw4+9FLF9EG/1PkY0ZN5IATOj5C51sup0oxeF69deZcpvlbc5CGLrktU9eB+a5pb517xyU0anhVFQXxt2HItNYjG94i4yNUrhXrhX+W5T+w5/rd0Jb1pF0FLhgG64PN3do31zBeIFHexxtJI+hw=
  - secure: kOz5TougxvfO4Nj9MWDmW8e9q2iWlITlpyiKjiXJs4YRye4qQA/hu2jXYT9eUjN/OWv/TRRi2w7iwogZxWMwehH7a9yLauQ3tASHDtUdnA1YYJJM+hXgeKZszlJAo8wEKn3ySeHOKe3NUwt4rJ+oJLZliuiKp4wjOrcj9HEyB6jas6FlkQu2VAOt1OrK8iw1UsjykczbYYailCe7nbcaAit4vA1teuxPX+SK6Bo6Lj4s+mSuSFktW24n4b0DESKj/EkFMl8leTBaDF6+goWy/7tDKtUVKXi1OmyhRHtFNSfoKfYqLxMqCJ6YK7dHWPlK0hVnJ74koWyFMMdIPzo1X+i0xdJ3lc4hh/5ad9xPzK3BrhhNW/JGom5meVeTRju/eSo577WkftWxzpZ3tZClBf34eYwSzTvi7sLJXE8nz2xuhDUPfvpkETDkga2bkMpfbXyhHzTaoHv7HMXEdJqWyKmmSpFJd4X/2LhLctVCZ6UYgFFu++P2gRFdG4JqnAt9NiSx7X+2+iD0osehCCD5Xz/o0TwtglTyNdT0zHBWiMyLEPJZ7qB5X8zKrqjUvsdIEKPBjzK8dl/TDkaAz5ScLKHm7ZRIjqfUgIYaX9RpDMciun7sO6R2v3zvglCubhJ5JeSRZU3G2ef83T/W4w09Ti6QmZS2r4lEJi0Mg1bHog4=
  - secure: mFMDkoWE2WP7DOT/+ipd6ExOREX/qBDRSzHuR642yPJu3LkrLiNZVl6Ux3Ss49ZosJT5Dwwg0zKKBbMnD+IRmEk9sLTs6ATnAOeGB7uO5HI60dNKk2+zOZzbXZ1zoer1iC0StgnS/mCzT1KIegkGcm52tg8zNfs0aUTk9IHDlZNtmpKPgP7uOz0bA9YRC4UOc2UR6H/G3ZOSVLXrzXjtrZ2+IAHN80WEPD83xop8L/dN91nxU4nCFcx2cQR7olwp24FmzCmizRRCj/OLqYxmXl8KAES6im1AVxOOIsZUAj5pKKWu/jd5blkZnVmKa//2X2X2Ii3G1ahcvJ1UVNOU8C+2KrhaowGKB0KpRqnoahZcV3HDvvOzdGrerCojozNBzCicT2DXYF0x0GiGd2ohoT/jEv1YuG1j6MTxgEwyl7Olue5JmZOe194lztknlNT0FAfzt4yGTsgHKaTDiQ3Ldq5rQqPGDHjvrY30RYJqxdNcBiDWP3J1ilGY+OYywbW0X5OGpgBrozvXKWd6RpgvpMn/wAHuQAM84sCaGNrnXG9cw7Pct/zcW9Tk7/hSPUuVweMz9syf2cj5WssJ8zY8CgocoEgC9xjwJbsOHRjUYLnayILREfE1TO2uN89D6E1imU63Whllx8kkRCFiNoKhGjYRbTZ4oboBmwLqCNdO5U0=
cache:
  directories:
  - "~/.m2/repository"
before_deploy:
  - "./cd/before-deploy.sh"
deploy:
  # deploy to snapshot repo
  - provider: script
    script: mvn deploy -P sign,build-extras -s cd/maven-settings.xml -DskipTests
    skip_cleanup: true
    on:
      branch: master
  # deploy to releases
  - provider: script
    script: mvn versions:set -DnewVersion=${TRAVIS_TAG:1} && mvn deploy -P sign,build-extras -s cd/maven-settings.xml -DskipTests
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
# safelist
branches:
  only:
    - master
    - /^v\d+\.\d+.\d+$/